In [1]:
import pandas as pd
from datetime import timedelta
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
df = pd.read_csv("csv_files\df.csv")
df2 = pd.read_csv("csv_files\df2.csv")

In [3]:
df['Order date'] = pd.to_datetime(df['Order date'])
cus_data = df.groupby('Custumer Id').get_group(750)
cus_data.sort_values('Order date',inplace=True)
cus_data

<ipython-input-3-3d06133965f6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cus_data.sort_values('Order date',inplace=True)

,Order date,Custumer Id,Item Id,Country,State,City,Subgruop_ID,Quantity
8567,2019-10-25,750,30510003,1,16,52,51,5.0
8594,2019-10-25,750,30700010,1,16,52,70,60.0
8595,2019-10-25,750,30700013,1,16,52,70,2.0
8596,2019-10-25,750,30700018,1,16,52,70,2.0
8597,2019-10-25,750,30700019,1,16,52,70,80.0
...,...,...,...,...,...,...,...,...
242148,2021-09-03,750,30600048,1,16,52,60,60.0
242147,2021-09-03,750,30600046,1,16,52,60,20.0
242146,2021-09-03,750,30600045,1,16,52,60,100.0
242144,2021-09-03,750,30600043,1,16,52,60,10.0
242223,2021-09-03,750,30710005,1,16,52,71,4.0

In [4]:
cus_data.groupby('Order date').groups.keys()

dict_keys([Timestamp('2019-10-25 00:00:00'), Timestamp('2020-01-08 00:00:00'), Timestamp('2020-02-13 00:00:00'), Timestamp('2020-04-28 00:00:00'), Timestamp('2020-05-22 00:00:00'), Timestamp('2020-07-02 00:00:00'), Timestamp('2020-08-07 00:00:00'), Timestamp('2020-10-05 00:00:00'), Timestamp('2020-12-14 00:00:00'), Timestamp('2021-02-16 00:00:00'), Timestamp('2021-04-19 00:00:00'), Timestamp('2021-07-06 00:00:00'), Timestamp('2021-09-03 00:00:00')])

In [5]:
dir(cus_data.groupby('Order date'))

['City',
 'Country',
 'Quantity',
 'State',
 'Subgruop_ID',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_agg_examples_doc',
 '_agg_general',
 '_aggregate_frame',
 '_aggregate_item_by_item',
 '_aggregate_with_numba',
 '_apply_allowlist',
 '_apply_filter',
 '_apply_to_column_groupbys',
 '_assure_grouper',
 '_bool_agg',
 '_builtin_table',
 '_choose_path',
 '_concat_objects',
 '_constructor',
 '_cumcount_array',
 '_cython_agg_blocks',
 '_cython_agg_general',
 '_cython_table',
 '_cython_transform',
 '_define_paths',
 '_dir_additions',
 '_dir_deletions',
 '_fill',
 '_get_cython_func',
 '_get_cythonized_result',
 '_get_data_to_aggregate',
 '_get_index',
 '_get_indices',
 '_gotitem',
 '_group_selection',
 '_hidden_attrs',
 '_insert_inaxis_grouper_inplace',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_protocol',
 '_iterate_column_groupbys',
 '_iterate_slices',
 '_make_wrapper',
 '_obj_1d_constructor',
 '_obj_with_exclusions',
 '_python_agg_general',
 '_python_apply_general',
 '_reindex_output',
 '_reset_cache',
 '_reset_group_selection',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_group_selection',
 '_set_result_index_ordered',
 '_transform_fast',
 '_transform_general',
 '_transform_item_by_item',
 '_transform_with_numba',
 '_try_aggregate_string_function',
 '_wrap_agged_blocks',
 '_wrap_aggregated_output',
 '_wrap_applied_output',
 '_wrap_applied_output_series',
 '_wrap_frame_output',
 '_wrap_transformed_output',
 'agg',
 'aggregate',
 'all',
 'any',
 'apply',
 'backfill',
 'bfill',
 'boxplot',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cumcount',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'dtypes',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'get_group',
 'groups',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'indices',
 'last',
 'mad',
 'max',
 'mean',
 'median',
 'min',
 'ndim',
 'ngroup',
 'ngroups',
 'nth',
 'nunique',
 'ohlc',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'prod',
 'quantile',
 'rank',
 'resample',
 'rolling',
 'sample',
 'sem',
 'shift',
 'size',
 'skew',
 'std',
 'sum',
 'tail',
 'take',
 'transform',
 'tshift',
 'var']

In [6]:
cus_data.groupby('Order date').get_group('2019-10-25')

,Order date,Custumer Id,Item Id,Country,State,City,Subgruop_ID,Quantity
8567,2019-10-25,750,30510003,1,16,52,51,5.0
8594,2019-10-25,750,30700010,1,16,52,70,60.0
8595,2019-10-25,750,30700013,1,16,52,70,2.0
8596,2019-10-25,750,30700018,1,16,52,70,2.0
8597,2019-10-25,750,30700019,1,16,52,70,80.0
8598,2019-10-25,750,30700020,1,16,52,70,100.0
8599,2019-10-25,750,30700021,1,16,52,70,4.0
8600,2019-10-25,750,30700022,1,16,52,70,20.0
8601,2019-10-25,750,30700030,1,16,52,70,10.0
8603,2019-10-25,750,30700041,1,16,52,70,2.0
8604,2019-10-25,750,30700043,1,16,52,70,8.0
8605,2019-10-25,750,30700051,1,16,52,70,2.0
8606,2019-10-25,750,30700054,1,16,52,70,20.0
8607,2019-10-25,750,30700061,1,16,52,70,1.0
8608,2019-10-25,750,30700062,1,16,52,70,2.0
8609,2019-10-25,750,30700082,1,16,52,70,8.0
8610,2019-10-25,750,30700093,1,16,52,70,20.0
8611,2019-10-25,750,30700095,1,16,52,70,4.0
8612,2019-10-25,750,30700124,1,16,52,70,1.0
8613,2019-10-25,750,30700147,1,16,52,70,1.0
8614,2019-10-25,750,30700205,1,16,52,70,2.0
8615,2019-10-25,750,30710001,1,16,52,71,8.0
8593,2019-10-25,750,30700008,1,16,52,70,15.0
8592,2019-10-25,750,30700004,1,16,52,70,50.0
8602,2019-10-25,750,30700037,1,16,52,70,2.0
8590,2019-10-25,750,30610062,1,16,52,61,6.0
8568,2019-10-25,750,30510017,1,16,52,51,30.0
8591,2019-10-25,750,30610153,1,16,52,61,10.0
8570,2019-10-25,750,30510076,1,16,52,51,5.0
8571,2019-10-25,750,30520004,1,16,52,52,30.0
8572,2019-10-25,750,30520014,1,16,52,52,50.0
8573,2019-10-25,750,30520021,1,16,52,52,50.0
8574,2019-10-25,750,30530023,1,16,52,53,10.0
8575,2019-10-25,750,30600014,1,16,52,60,10.0
8576,2019-10-25,750,30600035,1,16,52,60,40.0
8577,2019-10-25,750,30600042,1,16,52,60,80.0
8578,2019-10-25,750,30600044,1,16,52,60,10.0
8569,2019-10-25,750,30510026,1,16,52,51,10.0
8580,2019-10-25,750,30600048,1,16,52,60,40.0
8579,2019-10-25,750,30600045,1,16,52,60,50.0
8588,2019-10-25,750,30610048,1,16,52,61,6.0
8587,2019-10-25,750,30610007,1,16,52,61,4.0
8586,2019-10-25,750,30600185,1,16,52,60,10.0
8585,2019-10-25,750,30600154,1,16,52,60,40.0
8589,2019-10-25,750,30610049,1,16,52,61,10.0
8583,2019-10-25,750,30600091,1,16,52,60,30.0
8582,2019-10-25,750,30600057,1,16,52,60,10.0
8581,2019-10-25,750,30600051,1,16,52,60,10.0
8584,2019-10-25,750,30600153,1,16,52,60,10.0

In [7]:
#for date in cus_data['Order date'].unique():

prepare data till date
number of orders, number of orders by Items (freq), number of days since last order (Item wise)

In [8]:
def itemwise_freq(cus_data):
    freq_itemwise = {}
    x = cus_data['Order date']
    for i in x.index:
        freq_itemwise[i] = x[i]/x.sum()
    return freq_itemwise

In [11]:
def num_days_since_last(itemwise_data):
    last_buy = {}
    for item_id in cus_data['Item Id'].unique():
        x = itemwise_data.get_group(item_id).reset_index()
        if len(x) > 1:
            last_buy[item_id] = (x.iloc[len(x)-1]['Order date'] - x.iloc[len(x)-2]['Order date']).days
    return last_buy

In [12]:
def data_till_date(cus_id):
    cus_data = df.groupby('Custumer Id').get_group(cus_id)
    number_of_orders = len(cus_data.groupby('Order date').count())
    itemwise_data = itemwise_freq(cus_data.groupby('Item Id').count())
    last_ord = num_days_since_last(cus_data.groupby('Item Id'))